use algonauts_db;
-- Inserting top technical skills into the TechSkills table
INSERT INTO TechSkills (skill_name, complexity, category, popularity_score, description) VALUES
    -- Programming Languages
    ('Python', 'Beginner', 'Programming Language', 95.00, 'A versatile high-level programming language known for its readability and broad applicability.'),
    ('JavaScript', 'Beginner', 'Programming Language', 90.00, 'A core technology of the World Wide Web, enabling interactive web pages.'),
    ('Java', 'Intermediate', 'Programming Language', 85.00, 'A class-based, object-oriented programming language designed for portability across platforms.'),
    ('C++', 'Advanced', 'Programming Language', 80.00, 'An extension of C programming language with object-oriented features, widely used in system/software development.'),
    ('C#', 'Intermediate', 'Programming Language', 75.00, 'A language developed by Microsoft, primarily for the .NET framework, combining principles from C and C++.'),
    ('Ruby', 'Beginner', 'Programming Language', 70.00, 'A dynamic, open-source programming language with a focus on simplicity and productivity.'),
    ('PHP', 'Beginner', 'Programming Language', 65.00, 'A server-side scripting language designed for web development but also used as a general-purpose language.'),
    ('Swift', 'Intermediate', 'Programming Language', 60.00, 'A powerful and intuitive programming language for macOS, iOS, watchOS, and tvOS app development.'),
    ('Kotlin', 'Intermediate', 'Programming Language', 55.00, 'A statically typed programming language for modern multiplatform applications, fully interoperable with Java.'),
    ('Go', 'Intermediate', 'Programming Language', 50.00, 'An open-source programming language that makes it easy to build simple, reliable, and efficient software.'),
    ('R', 'Intermediate', 'Programming Language', 45.00, 'A language and environment for statistical computing and graphics, widely used among statisticians and data miners.'),
    ('SQL', 'Beginner', 'Database Language', 95.00, 'A standard language for managing and manipulating relational databases.'),
    ('HTML', 'Beginner', 'Markup Language', 90.00, 'The standard markup language for documents designed to be displayed in a web browser.'),
    ('CSS', 'Beginner', 'Style Sheet Language', 85.00, 'A style sheet language used for describing the presentation of a document written in HTML or XML.'),
    ('TypeScript', 'Intermediate', 'Programming Language', 80.00, 'A strict syntactical superset of JavaScript that adds optional static typing.'),
    ('Scala', 'Advanced', 'Programming Language', 75.00, 'A strong static type language that combines object-oriented and functional programming.'),
    ('Perl', 'Intermediate', 'Programming Language', 70.00, 'A family of two high-level, general-purpose, interpreted, dynamic programming languages.'),
    ('Rust', 'Advanced', 'Programming Language', 65.00, 'A language empowering everyone to build reliable and efficient software, focusing on safety and performance.'),
    ('Dart', 'Intermediate', 'Programming Language', 60.00, 'A client-optimized language for fast apps on any platform, developed by Google.'),
    ('Shell Scripting', 'Beginner', 'Scripting Language', 55.00, 'Writing scripts for command-line interpreters to automate tasks in Unix/Linux environments.'),
    ('MATLAB', 'Intermediate', 'Programming Language', 50.00, 'A programming platform designed specifically for engineers and scientists.'),
    ('Objective-C', 'Intermediate', 'Programming Language', 45.00, 'A general-purpose, object-oriented programming language that adds Smalltalk-style messaging to C.'),
    ('Assembly Language', 'Advanced', 'Programming Language', 40.00, 'A low-level programming language for a computer or other programmable device specific to a particular computer architecture.'),
    ('VHDL', 'Advanced', 'Hardware Description Language', 35.00, 'A hardware description language used in electronic design automation to describe digital and mixed-signal systems.'),
    ('Verilog', 'Advanced', 'Hardware Description Language', 30.00, 'A hardware description language used to model electronic systems.'),
    ('SAS', 'Intermediate', 'Statistical Software', 25.00, 'A software suite developed by SAS Institute for advanced analytics, multivariate analysis, business intelligence, and data management.'),
    ('COBOL', 'Intermediate', 'Programming Language', 20.00, 'A compiled English-like computer programming language designed for business use.'),
    ('Fortran', 'Intermediate', 'Programming Language', 15.00, 'A general-purpose, compiled imperative programming language that is especially suited to numeric computation and scientific computing.'),
    ('Haskell', 'Advanced', 'Programming Language', 10.00, 'A standardized, general-purpose purely functional programming language, with non-strict semantics and strong static typing.'),
    ('Lua', 'Beginner', 'Programming Language', 5.00, 'A lightweight, high-level, multi-paradigm programming language designed primarily for embedded use in applications.'),
    -- Soft and Technical Skills
    ('Problem Solving', 'Intermediate', 'Soft Skill', 85.00, 'The process of finding solutions to complex or difficult issues.'),
    ('Software Tools Proficiency', 'Beginner', 'Technical Skill', 75.00, 'Ability to effectively use software tools for various applications.'),
    ('Academic Orientation', 'Beginner', 'Soft Skill', 65.00, 'Familiarity with academic environments and expectations.'),
    ('Professional Development', 'Intermediate', 'Soft Skill', 70.00, 'Skills aimed at improving professional capabilities and career advancement.'),
    ('Career Preparation', 'Intermediate', 'Soft Skill', 68.00, 'Readiness for entering and succeeding in a chosen career path.'),
    ('Co-op Readiness', 'Intermediate', 'Soft Skill', 66.00, 'Preparedness for cooperative education experiences.'),
    ('Discrete Mathematics', 'Intermediate', 'Mathematics', 80.00, 'Study of mathematical structures that are fundamentally discrete rather than continuous.'),
    ('Logical Reasoning', 'Intermediate', 'Soft Skill', 78.00, 'Ability to analyze and evaluate arguments and reasoning.'),
    ('Applied Discrete Mathematics', 'Intermediate', 'Mathematics', 77.00, 'Practical application of discrete mathematics concepts.'),
    ('Programming Fundamentals', 'Beginner', 'Technical Skill', 90.00, 'Basic concepts and techniques of programming.'),
    ('Algorithmic Thinking', 'Intermediate', 'Technical Skill', 85.00, 'Ability to solve problems using algorithms.'),
    ('Practical Programming', 'Beginner', 'Technical Skill', 88.00, 'Hands-on experience in writing and testing code.'),
    ('Debugging', 'Intermediate', 'Technical Skill', 82.00, 'Identifying and fixing errors in software code.'),
    ('Object-Oriented Programming', 'Intermediate', 'Technical Skill', 84.00, 'Programming paradigm based on the concept of objects.'),
    ('Data Structures', 'Intermediate', 'Technical Skill', 83.00, 'Organizing and storing data efficiently.'),
    ('Advanced Programming Techniques', 'Advanced', 'Technical Skill', 79.00, 'Complex programming methods and practices.'),
    ('Formal Logic', 'Intermediate', 'Mathematics', 76.00, 'Study of reasoning and argumentation.'),
    ('Computational Theory', 'Advanced', 'Mathematics', 74.00, 'Study of the capabilities and limitations of computing machines.'),
    ('Linear Algebra', 'Intermediate', 'Mathematics', 73.00, 'Branch of mathematics concerning linear equations and their representations.'),
    ('Multivariable Calculus', 'Advanced', 'Mathematics', 72.00, 'Extension of calculus to functions of multiple variables.'),
    ('Statistics', 'Intermediate', 'Mathematics', 81.00, 'Science of collecting, analyzing, and interpreting data.'),
    ('Algorithm Design', 'Advanced', 'Technical Skill', 75.00, 'Creating efficient algorithms to solve problems.'),
    ('Data Analysis', 'Intermediate', 'Technical Skill', 80.00, 'Inspecting and modeling data to discover useful information.'),
    ('Software Design Patterns', 'Advanced', 'Technical Skill', 78.00, 'General repeatable solutions to common software design problems.'),
    ('Object-Oriented Principles', 'Intermediate', 'Technical Skill', 77.00, 'Fundamental concepts of object-oriented programming.'),
    ('Software Implementation', 'Intermediate', 'Technical Skill', 76.00, 'Process of executing a plan or design in software development.'),
    ('Design Application', 'Intermediate', 'Technical Skill', 75.00, 'Applying design principles in practical scenarios.'),
    ('System Architecture', 'Advanced', 'Technical Skill', 74.00, 'Conceptual model defining the structure and behavior of a system.'),
    ('Operating Systems', 'Intermediate', 'Technical Skill', 73.00, 'Software that manages computer hardware and software resources.'),
    ('Networking Protocols', 'Intermediate', 'Technical Skill', 72.00, 'Rules and conventions for communication between network devices.'),
    ('Distributed Computing', 'Advanced', 'Technical Skill', 71.00, 'Computing processes distributed across multiple systems.'),
    ('Automata Theory', 'Advanced', 'Mathematics', 70.00, 'Study of abstract machines and problems they can solve.'),
    ('Complexity Theory', 'Advanced', 'Mathematics', 69.00, 'Study of the complexity of solving problems.'),
    ('Software Engineering', 'Intermediate', 'Technical Skill', 68.00, 'Application of engineering principles to software development.'),
    ('Project Management', 'Intermediate', 'Soft Skill', 67.00, 'Planning and executing projects efficiently.'),
    ('Software Development Life Cycle', 'Intermediate', 'Technical Skill', 66.00, 'Process of planning, creating, testing, and deploying software.'),
    ('Quality Assurance', 'Intermediate', 'Technical Skill', 65.00, 'Ensuring that products meet specified quality standards.'),
    ('Cybersecurity Principles', 'Intermediate', 'Technical Skill', 64.00, 'Fundamental concepts of protecting systems and data.'),
    ('Threat Analysis', 'Advanced', 'Technical Skill', 63.00, 'Identifying and evaluating potential security threats.'),
    ('System Vulnerability Assessment', 'Advanced', 'Technical Skill', 62.00, 'Identifying weaknesses in systems that could be exploited.'),
    ('Security Protocols', 'Advanced', 'Technical Skill', 61.00, 'Procedures and measures to protect data and systems.'),
    ('Network Defense', 'Advanced', 'Technical Skill', 60.00, 'Protecting computer networks from intrusions and attacks.'),
    ('Cryptography', 'Advanced', 'Technical Skill', 59.00, 'Practice of secure communication in the presence of adversaries.'),
    ('AI Algorithms', 'Advanced', 'Technical Skill', 58.00, 'Algorithms designed to perform tasks that typically require human intelligence.'),
    ('Machine Learning', 'Advanced', 'Technical Skill', 57.00, 'Study of computer algorithms that improve automatically through experience.');
-- Adding more skills to the TechSkills table
INSERT INTO TechSkills (skill_name, complexity, category, popularity_score, description) VALUES
    ('Unity/Unreal Engine Basics', 'Intermediate', 'Development Tool', 80.00, 'Foundational knowledge of game development platforms Unity and Unreal Engine.'),
    ('Cloud-Specific Security Concepts', 'Intermediate', 'Cloud Computing', 75.00, 'Understanding of security practices specific to cloud environments.'),
    ('3D Modeling', 'Intermediate', 'Design Skill', 85.00, 'Ability to create 3D models using software like AutoCAD or Blender.'),
    ('Quantum Theory Basics', 'Advanced', 'Mathematics', 90.00, 'Basic principles of quantum mechanics relevant to computing.'),
    ('Creative Writing Basics', 'Beginner', 'Creative Skill', 65.00, 'Skills to create narratives, particularly useful for storytelling in games.'),
    ('Cross-Platform Development', 'Intermediate', 'Programming Skill', 70.00, 'Developing software compatible with multiple platforms.'),
    ('Mobile UI/UX Design', 'Intermediate', 'Design Skill', 75.00, 'Creating intuitive interfaces for mobile applications.'),
    ('Web Performance Optimization', 'Intermediate', 'Web Development', 70.00, 'Techniques to improve the performance of web applications.'),
    ('Responsive Design', 'Intermediate', 'Web Development', 80.00, 'Designing applications to work seamlessly across devices.')

