use algonauts_db;
DESCRIBE CareerPaths;
-- Insert sample career paths into the CareerPaths table
INSERT INTO CareerPaths (career_name, description, salary, demand) VALUES
('Software Engineer', 'Designs, develops, and maintains software systems.', 120000, 4.5),
('Data Scientist', 'Analyzes and interprets complex data to help organizations make decisions.', 130000, 4.7),
('Cybersecurity Analyst', 'Protects an organization\'s systems and networks from cyber threats.', 110000, 4.6),
('AI/ML Engineer', 'Develops and implements machine learning and artificial intelligence solutions.', 140000, 4.8),
('Web Developer', 'Builds and maintains websites and web applications.', 85000, 4.3),
('Mobile App Developer', 'Designs and develops applications for mobile devices.', 100000, 4.4),
('Cloud Engineer', 'Manages and maintains cloud infrastructure and services.', 125000, 4.6),
('DevOps Engineer', 'Facilitates the integration and deployment of software systems.', 115000, 4.5),
('Network Administrator', 'Maintains and ensures the smooth operation of computer networks.', 95000, 4.2),
('Database Administrator', 'Manages and organizes an organization\'s databases.', 105000, 4.3),
('IT Project Manager', 'Oversees and manages IT projects within an organization.', 115000, 4.4),
('Game Developer', 'Designs and develops video games for various platforms.', 95000, 4.1),
('UX/UI Designer', 'Enhances user experience by designing user interfaces.', 90000, 4.2),
('Blockchain Developer', 'Develops and implements blockchain technologies and smart contracts.', 140000, 4.7),
('Robotics Engineer', 'Designs and builds robots and robotic systems.', 130000, 4.6),
('Systems Analyst', 'Evaluates and improves organizational IT systems.', 95000, 4.3),
('Embedded Systems Engineer', 'Develops software and hardware for embedded systems.', 110000, 4.4),
('Technical Writer', 'Creates technical documentation for systems and software.', 80000, 4.0),
('Quality Assurance Engineer', 'Tests and ensures the quality of software systems.', 90000, 4.2),
('IT Support Specialist', 'Provides technical support to resolve IT issues.', 65000, 4.1),
('AR/VR Developer', 'Designs and develops augmented reality and virtual reality experiences.', 120000, 4.5),
('Data Engineer', 'Builds and optimizes data pipelines and ensures data availability for analytics.', 115000, 4.6),
('Information Security Manager', 'Oversees and implements security measures to protect IT infrastructure.', 145000, 4.7),
('Machine Learning Researcher', 'Conducts research to improve and advance machine learning algorithms.', 150000, 4.8),
('Big Data Analyst', 'Examines large datasets to uncover trends and insights.', 125000, 4.5),
('Site Reliability Engineer', 'Ensures the reliability and performance of production systems.', 130000, 4.6),
('E-commerce Developer', 'Builds and maintains online shopping platforms.', 95000, 4.3),
('Bioinformatics Specialist', 'Applies computational techniques to analyze biological data.', 120000, 4.4),
('Full-Stack Developer', 'Works on both front-end and back-end aspects of web applications.', 115000, 4.5),
('Systems Architect', 'Designs high-level structures for IT systems and solutions.', 140000, 4.6),
('Penetration Tester', 'Identifies security vulnerabilities through ethical hacking.', 115000, 4.5),
('Digital Marketing Analyst', 'Leverages data analytics to optimize marketing campaigns.', 85000, 4.2),
('Product Manager', 'Coordinates the development and marketing of software products.', 125000, 4.4),
('Cloud Security Engineer', 'Focuses on securing cloud-based systems and data.', 135000, 4.6),
('Quantum Computing Researcher', 'Explores and develops quantum computing technologies.', 160000, 4.9),
('IoT Developer', 'Creates systems and applications for Internet of Things devices.', 110000, 4.4),
('Autonomous Vehicle Engineer', 'Develops systems for self-driving vehicles.', 145000, 4.7),
('Game Designer', 'Designs game mechanics and storylines for video games.', 90000, 4.1),
('IT Consultant', 'Provides expert advice to improve IT systems and processes.', 100000, 4.3),
('Technical Program Manager', 'Manages technical projects and cross-functional teams.', 135000, 4.5),
('Operations Analyst', 'Analyzes and optimizes business operations using IT tools.', 85000, 4.2),
('Health Informatics Specialist', 'Combines IT and healthcare to optimize patient care.', 95000, 4.3),
('Energy Systems Engineer', 'Develops software and systems for renewable energy solutions.', 125000, 4.5),
('Video Production Engineer', 'Focuses on tools and systems for video editing and production.', 80000, 4.0),
('Hardware Engineer', 'Designs and develops computer hardware components.', 115000, 4.4),
('Cryptographer', 'Develops algorithms and protocols to secure communications.', 140000, 4.6),
('3D Printing Specialist', 'Designs and builds models using additive manufacturing techniques.', 85000, 4.2),
('Digital Forensics Analyst', 'Investigates and recovers data related to cybercrime.', 105000, 4.3),
('Natural Language Processing Specialist', 'Develops systems for understanding and processing human language.', 135000, 4.6),
('Business Intelligence Analyst', 'Uses data to inform strategic business decisions.', 100000, 4.4),
('Audio Engineer', 'Designs and optimizes systems for sound recording and production.', 80000, 4.0),
('Digital Twin Engineer', 'Creates virtual models of physical assets for simulation and monitoring.', 120000, 4.5),
('Ethical Hacker', 'Tests security measures by simulating cyberattacks.', 115000, 4.5),
('Environmental Data Scientist', 'Analyzes data to support environmental research and policy.', 95000, 4.3),
('Game Tester', 'Tests video games for bugs, usability, and performance.', 65000, 4.1),
('Financial Systems Developer', 'Builds IT solutions for financial services.', 120000, 4.5);

