use algonauts_db;


-- Insert interview questions into the table
INSERT INTO InterviewQuestions (question, skill, difficulty) VALUES
('What is the difference between a process and a thread?', 'Operating Systems', 'Medium'),
('Explain how a hash table works.', 'Data Structures', 'Medium'),
('What is the time complexity of quicksort?', 'Algorithms', 'Medium'),
('How would you find the largest element in a binary search tree?', 'Data Structures', 'Easy'),
('Describe the difference between stack and heap memory.', 'Memory Management', 'Medium'),
('What is a deadlock? How can it be avoided?', 'Operating Systems', 'Hard'),
('Explain the concept of recursion with an example.', 'Programming Fundamentals', 'Easy'),
('How does dynamic programming improve algorithm efficiency?', 'Algorithms', 'Medium'),
('What is a race condition, and how can it be prevented?', 'Concurrency', 'Hard'),
('Describe the difference between TCP and UDP.', 'Networking', 'Medium'),
('How would you reverse a linked list?', 'Data Structures', 'Medium'),
('What are the main principles of Object-Oriented Programming?', 'OOP', 'Easy'),
('Explain the difference between abstraction and encapsulation.', 'OOP', 'Medium'),
('What is polymorphism? Provide an example.', 'OOP', 'Medium'),
('How would you implement a queue using stacks?', 'Data Structures', 'Hard'),
('What is the difference between BFS and DFS?', 'Algorithms', 'Medium'),
('How does a garbage collector work in programming languages?', 'Memory Management', 'Medium'),
('Explain the CAP theorem in distributed systems.', 'Distributed Systems', 'Hard'),
('What is the difference between NoSQL and SQL databases?', 'Databases', 'Medium'),
('How does an index improve query performance in a database?', 'Databases', 'Medium'),
('What are RESTful APIs, and why are they used?', 'Web Development', 'Easy'),
('Explain how HTTPS ensures secure communication.', 'Networking', 'Medium'),
('What is the difference between authentication and authorization?', 'Security', 'Easy'),
('Describe how a binary search works.', 'Algorithms', 'Easy'),
('How would you detect a cycle in a directed graph?', 'Algorithms', 'Hard'),
('Explain how caching improves performance.', 'System Design', 'Medium'),
('What is a load balancer, and how does it work?', 'System Design', 'Medium'),
('How would you design a URL shortening service?', 'System Design', 'Hard'),
('What is the difference between GET and POST in HTTP?', 'Web Development', 'Easy'),
('What is the purpose of a virtual memory system?', 'Operating Systems', 'Medium'),
('How do you implement thread synchronization?', 'Concurrency', 'Hard'),
('What is the difference between an abstract class and an interface?', 'OOP', 'Medium'),
('Explain how to implement a priority queue.', 'Data Structures', 'Medium'),
('What is the difference between a shallow copy and a deep copy?', 'Programming Fundamentals', 'Medium'),
('What is a mutex, and how is it used?', 'Concurrency', 'Hard'),
('How does DNS work?', 'Networking', 'Medium'),
('What are the different types of joins in SQL?', 'Databases', 'Medium'),
('Explain the purpose of normalization in a database.', 'Databases', 'Medium'),
('What is the difference between linear search and binary search?', 'Algorithms', 'Easy'),
('How would you count the number of set bits in an integer?', 'Bit Manipulation', 'Hard'),
('What is a CDN, and how does it work?', 'Networking', 'Medium'),
('What are the differences between microservices and monolithic architectures?', 'System Design', 'Medium'),
('How would you implement a singleton design pattern?', 'Design Patterns', 'Medium'),
('Explain how you would find the shortest path in a weighted graph.', 'Algorithms', 'Hard'),
('What is a firewall, and how does it protect a network?', 'Security', 'Medium'),
('Describe how an operating system schedules processes.', 'Operating Systems', 'Medium'),
('What is the difference between symmetric and asymmetric encryption?', 'Security', 'Medium'),
('How does a compiler convert high-level code to machine code?', 'Programming Fundamentals', 'Medium'),
('What is the purpose of a semaphore?', 'Concurrency', 'Hard'),
('What are the key differences between IPv4 and IPv6?', 'Networking', 'Medium'),
('How does a search engine rank web pages?', 'Web Development', 'Medium'),
('What are the SOLID principles in software design?', 'Software Engineering', 'Medium'),
('How would you implement a hash map from scratch?', 'Data Structures', 'Hard'),
('What is a trie, and where is it used?', 'Data Structures', 'Medium'),
('Explain the difference between synchronous and asynchronous programming.', 'Programming Fundamentals', 'Medium'),
('What is the sliding window technique?', 'Algorithms', 'Medium'),
('How would you design a file-sharing system like Dropbox?', 'System Design', 'Hard'),
('What is an API gateway?', 'System Design', 'Medium'),
('Describe the difference between vertical and horizontal scaling.', 'System Design', 'Medium'),
('How does garbage collection work in Java?', 'Memory Management', 'Medium'),
('What is a relational database, and how is it structured?', 'Databases', 'Easy'),
('How does a web browser render a webpage?', 'Web Development', 'Medium'),
('Explain what a distributed hash table is.', 'Distributed Systems', 'Hard'),
('How would you sort an array of integers without using a built-in sort function?', 'Algorithms', 'Easy'),
('What is memoization, and how is it used in dynamic programming?', 'Algorithms', 'Medium'),
('Describe the steps to create a secure login system.', 'Security', 'Hard'),
('How does OAuth2 work?', 'Security', 'Medium'),
('What is the purpose of a model-view-controller (MVC) architecture?', 'Software Engineering', 'Medium'),
('Explain how a blockchain works.', 'Distributed Systems', 'Hard'),
('How would you prevent SQL injection attacks?', 'Security', 'Medium'),
('What is the difference between Docker and a virtual machine?', 'DevOps', 'Medium'),
('How does version control work in Git?', 'Software Engineering', 'Easy'),
('What is the difference between compile-time and runtime errors?', 'Programming Fundamentals', 'Easy'),
('How does a web server handle multiple requests simultaneously?', 'Web Development', 'Medium'),
('What is the purpose of an access control list (ACL)?', 'Security', 'Medium'),
('How would you handle collisions in a hash table?', 'Data Structures', 'Medium'),
('What is the difference between an iterative and recursive solution?', 'Programming Fundamentals', 'Easy'),
('How would you optimize a slow SQL query?', 'Databases', 'Hard'),
('Explain what the observer design pattern is.', 'Design Patterns', 'Medium'),
('What is a buffer overflow, and how can it be prevented?', 'Security', 'Hard'),
('How does the OS handle context switching?', 'Operating Systems', 'Medium'),
('What are the differences between static and dynamic linking?', 'Operating Systems', 'Medium'),
('How would you detect and resolve deadlocks in a system?', 'Concurrency', 'Hard');

describe CodingAssessments;
INSERT INTO CodingAssessments (skill_id, problem_statement, input_example, expected_output) VALUES
-- Python
((SELECT tech_skill_id FROM TechSkills WHERE skill_name = 'Python'),
 'Write a function to calculate the factorial of a number using recursion.',
 'Input: 5',
 'Output: 120'),

((SELECT tech_skill_id FROM TechSkills WHERE skill_name = 'Python'),
 'Write a Python function to check if a string is a palindrome.',
 'Input: "radar"',
 'Output: True'),

((SELECT tech_skill_id FROM TechSkills WHERE skill_name = 'Python'),
 'Write a Python script to generate the first n Fibonacci numbers.',
 'Input: 7',
 'Output: [0, 1, 1, 2, 3, 5, 8]'),

((SELECT tech_skill_id FROM TechSkills WHERE skill_name = 'Python'),
 'Write a Python function to find the maximum value in a list.',
 'Input: [4, 2, 9, 7]',
 'Output: 9');
